name: PR CI build

on:
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      # Beginning of yarn setup
      - name: use node.js 20.x
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/ # Needed for auth
      - name: cache all node_modules
        id: cache-modules
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock', '**/package.json') }}
      - name: find location of global yarn cache
        id: yarn-cache
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: cache global yarn cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        if: steps.cache-modules.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        run: yarn install --immutable
      # End of yarn setup

      - name: knip
        run: yarn knip

      - name: lint
        run: yarn backstage-cli repo lint

      - name: deprecations
        run: yarn backstage-cli repo list-deprecations

      - name: type checking and declarations
        run: yarn tsc:full

      - name: tests
        run: yarn backstage-cli repo test

      - name: config check
        run: |
          yarn backstage-cli config:check --lax --strict
          yarn backstage-cli config:check --lax --strict --config app-config.yaml --config app-config.heroku.yaml

      - name: docker build
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -t example .
